version: '3.5'

networks:
    asker:
        name: asker

services:
    db:
        image: mariadb:10.3.7
        restart: always
        ports:
            - "3310:3306"
        environment:
            MYSQL_ROOT_PASSWORD: nicegame14
            MYSQL_DATABASE: wishket_purple
            MYSQL_USER: wishket
            MYSQL_PASSWORD: nicegame14
        networks:
            - asker
        healthcheck:
            test: ["CMD", "/usr/bin/mysql", "--user=wishket", "--password=nicegame14", "--execute", "SHOW DATABASES;"]
            interval: 5s
            timeout: 5s
            retries: 5
    web:
        build: .
        command: bash -c "cd /app/source && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app
        restart: on-failure
        ports:
            - "8001:8000"
        depends_on:
            - db
        networks:
            - asker
